#!/bin/bash


##function definitions
function start_psql {
    su - postgres -c "pg_ctl start -D /var/lib/postgres/data -l /var/log/postgres/log"
    echo '### starting database server ###'
}


if [ "$DB_EXTERNAL" = false ]; then

    if [ ! -d /var/lib/postgres/data/base ]; then

        echo '### no local postgres database found ###'
        echo '### installing database ###'

        chown postgres:postgres /var/lib/postgres/data
        chmod u=rwx,g-rwx,o-rwx /var/lib/postgres/data
        su - postgres -c "initdb --locale en_US.UTF-8 -E UTF8 -D '/var/lib/postgres/data'"
        start_psql
        sleep 2 #wait for postgres till started
        echo '### create Owncloud Database and -user ###'
        su - postgres -c "psql -c \"CREATE USER $DB_USER WITH PASSWORD '$DB_PASS';\""  
        su - postgres -c "psql -c \"CREATE DATABASE $DB_NAME OWNER $DB_USER;;\""
    else
        echo '### existing postgres database found ###'
        start_psql
    fi 

fi


   
if [ ! -d /srv/http/config ]; then
    
    echo '### downloading owncloud webinstaller ###'
    curl https://download.owncloud.com/download/community/setup-owncloud.php > /srv/http/setup-owncloud.php
    
    echo '### creating data-dir ###'
    mkdir "$OC_DATADIR"
    chown -R http:http /srv/http/
    
    echo '### running owncloud webinstaller ###'
    echo '...this may take a while...'
    echo ""| php -R 'include("/srv/http/setup-owncloud.php");' -B 'parse_str($argv[1], $_GET);' 'step=2&directory=.'


    echo '### writing config-files ###'
    #enable memcache
    #notice: here-documents only support real tabs
	cat <<-EOF >/srv/http/config/config.php
		<?php
		\$CONFIG = array (
			'memcache.local' => '\\\\OC\\\\Memcache\\\\XCache',
		);
	EOF

    #write autoconfig
    #notice: here-documents only support real tabs
	cat <<-EOF >/srv/http/config/autoconfig.php
		<?php
		\$AUTOCONFIG = array (
		"dbtype"        => "$DB_TYPE",
		"dbname"        => "$DB_NAME",
		"dbuser"        => "$DB_USER",
		"dbpass"        => "$DB_PASS",
		"dbhost"        => "$DB_HOST",
		"dbtableprefix" => "$DB_PREFIX",
		"adminlogin"    => "$OC_ADMIN",
		"adminpass"     => "$OC_ADMINPASS",
		"directory"     => "$OC_DATADIR",
		);
	EOF
 
 

    echo '### fixing directory premissions ###'    
    #from https://doc.owncloud.org/server/8.0/admin_manual/installation/installation_wizard.html
    ocpath='/srv/http'
    htuser='http'
    htgroup='http'

    find ${ocpath}/ -type f -print0 | xargs -0 chmod 0640
    find ${ocpath}/ -type d -print0 | xargs -0 chmod 0750
    
    chown -R root:${htuser} ${ocpath}/
    chown -R ${htuser}:${htgroup} ${ocpath}/apps/
    chown -R ${htuser}:${htgroup} ${ocpath}/config/
    chown -R ${htuser}:${htgroup} ${ocpath}/data/
    chown -R ${htuser}:${htgroup} ${ocpath}/themes/
    
   
    echo '### Gratulations! Point your browser to your new owncloud instance. ###'

fi


exec $@
