#!/bin/bash


##function definitions
function start_psql {
    echo '### starting database server ###'
    su - postgres -c "pg_ctl start -D /var/lib/postgres/data -l /var/log/postgres/log"
}


if [ "$DB_EXTERNAL" = false ]; then

    if [ ! -d /var/lib/postgres/data/base ]; then

        echo '### no local postgres database found ###'
        echo '### installing database ###'

        chown postgres:postgres /var/lib/postgres/data
        chmod u=rwx,g-rwx,o-rwx /var/lib/postgres/data
        su - postgres -c "initdb --locale en_US.UTF-8 -E UTF8 -D '/var/lib/postgres/data'"
        start_psql
        sleep 2 #wait for postgres till started
        echo '### create Owncloud Database and -user ###'
        su - postgres -c "psql -c \"CREATE USER $DB_USER WITH PASSWORD '$DB_PASS';\""  
        su - postgres -c "psql -c \"CREATE DATABASE $DB_NAME OWNER $DB_USER;;\""
    else
        echo '### existing postgres database found ###'
        start_psql
    fi 

fi


   
if [ ! -e /srv/http/index.php ]; then
    
    echo '### no owncloud webfiles found ###'  
    echo '### downloading owncloud webinstaller ###'
    curl https://download.owncloud.com/download/community/setup-owncloud.php > /srv/http/setup-owncloud.php
   
    echo '### running owncloud webinstaller ###'
    echo '...this may take a while...'
    echo ""| php -R 'include("/srv/http/setup-owncloud.php");' -B 'parse_str($argv[1], $_GET);' 'step=2&directory=.'
fi

if [ ! -e /srv/http/data/config/config.php ]; then
    
    echo '### no owncloud config-files found ###'
    mkdir -p data
    mv -f config data/
    mv -f apps data/
    ln -s data/config config
    ln -s data/apps apps

    echo '### writing config-files ###'
    #enable memcache
    #notice: here-documents only support real tabs
	cat <<-EOF >/srv/http/data/config/config.php
		<?php
		\$CONFIG = array (
			'memcache.local' => '\\OC\\Memcache\\APCu',
		);
	EOF

    #write autoconfig
    #notice: here-documents only support real tabs
	cat <<-EOF >/srv/http/data/config/autoconfig.php
		<?php
		\$AUTOCONFIG = array (
		"dbtype"        => "$DB_TYPE",
		"dbname"        => "$DB_NAME",
		"dbuser"        => "$DB_USER",
		"dbpass"        => "$DB_PASS",
		"dbhost"        => "$DB_HOST",
		"dbtableprefix" => "$DB_PREFIX",
		"adminlogin"    => "$OC_ADMIN",
		"adminpass"     => "$OC_ADMINPASS",
		"directory"     => "$OC_DATADIR",
		);
	EOF

else
   
   echo '### existing config-files found, migrating... ###' 
   rm -rf /srv/http/config
   rm -rf /srv/http/apps
   ln -s data/config config
   ln -s data/apps apps

fi

    echo "### set timezone to $OC_TIME ###"
    ln -sf /usr/share/zoneinfo/$OC_TIME /etc/localtime

    echo '### fixing directory premissions ###'    
    #from https://doc.owncloud.org/server/8.0/admin_manual/installation/installation_wizard.html
    ocpath='/srv/http'
    htuser='http'
    htgroup='http'

    find ${ocpath}/ -type f -print0 | xargs -0 chmod 0640
    find ${ocpath}/ -type d -print0 | xargs -0 chmod 0750
    
    chown -R root:${htuser} ${ocpath}/
    chown -R ${htuser}:${htgroup} ${ocpath}/apps/
    chown -R ${htuser}:${htgroup} ${ocpath}/config/
    chown -R ${htuser}:${htgroup} ${OC_DATADIR}
    chown -R ${htuser}:${htgroup} ${ocpath}/themes/
   
    chown -R root:root /ssl/
    chmod 600 /ssl
    chmod -R 700  /ssl/
   
    chmod +x /srv/http/occ

    echo '### configuring apache ###'
    sed -i 's/ServerAdmin.*$/ServerAdmin '"$OC_EMAIL"'/g' /etc/httpd/conf/httpd.conf 
    sed -i 's/ServerName.*$/ServerName '"$OC_DOMAIN"'/g' /etc/httpd/conf/httpd.conf 
    
    if [ "$OC_BACKUP_CRON" != "no" ]; then
       echo "### set up backup cron ###"
       fcron -b -p /var/log/cron.log
       echo "OC_BACKUP_FILES=$OC_BACKUP_FILES
       $OC_BACKUP_CRON /usr/local/bin/backup -b 2>&1 | tee /var/log/backup.log"| fcrontab - 
    fi
 
    rm -f /srv/http/setup-owncloud.php

    echo '### Gratulations! Point your browser to your new owncloud instance. ###'

exec $@
